version: '3.8'

services:
  app:
    container_name: lotocroot-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENT_ID: ${NEXT_PUBLIC_CLIENT_ID}
        NEXT_PUBLIC_REDIRECT_URI: ${NEXT_PUBLIC_REDIRECT_URI}
        NEXT_PUBLIC_TWITCH_CLIENT_ID: ${NEXT_PUBLIC_TWITCH_CLIENT_ID}
        NEXT_PUBLIC_TWITCH_REDIRECT_URI: ${NEXT_PUBLIC_TWITCH_REDIRECT_URI}
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CLIENT_ID=${NEXT_PUBLIC_CLIENT_ID}
      - NEXT_PUBLIC_REDIRECT_URI=${NEXT_PUBLIC_REDIRECT_URI}
      - DONATION_ALERTS_CLIENT_SECRET=${DONATION_ALERTS_CLIENT_SECRET}
      - NEXT_PUBLIC_TWITCH_CLIENT_ID=${NEXT_PUBLIC_TWITCH_CLIENT_ID}
      - NEXT_PUBLIC_TWITCH_REDIRECT_URI=${NEXT_PUBLIC_TWITCH_REDIRECT_URI}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}